### ISSUE TITLE
Refactor Calculator Component to Functional Component with Hooks

### ISSUE THREAD

**Issue by Charzy-1** [Charzy-1/Math-wizard-app#4]
### Summary
I've implemented the `Calculator.js` component in my React project as a functional component using React hooks (`useState`). This component handles basic arithmetic operations and updates the display based on user interactions.

### What I Did
- Implemented the `Calculator` as a functional component using React's `useState` hook.
- Managed state for `total`, `next`, and `operation`.
- Added event handlers to process user inputs and perform calculations based on logic from `calculate.js` and `operate.js`.

### Areas for Review
- Use of the `useState` hook for managing the calculator's state.
- Event handling and PropTypes validation for the `Button` component.
- General best practices for functional components in React.

### Additional Notes
The functionality is consistent with the original class-based implementation. I'm looking for feedback on how to improve code quality or optimize the implementation.

**Comment by Pamphilemkp** [comment]
Hi @Charzy-1, good so far, your code is complete and it is good that you used functional components.
To improve and refactor your code base based on analyses, here are a few steps you can follow:

### 1. **Extract Button Components Dynamically**
   - Instead of writing each button separately, you can create an array of button configurations and map over it to generate the buttons dynamically. This makes the code more DRY (Don't Repeat Yourself).

### 2. **Use `PropTypes` Shape for Better Validation**
   - You can use `PropTypes.shape` to define the shape of `calculatorState` and validate it in the component.

### 3. **Use CSS Modules or Styled Components**
   - If you’re using CSS Modules, consider converting the CSS to a module or using a CSS-in-JS solution like `styled-components`.

### 4. **Improve Code Structure**
   - You can organize the components into separate files if they grow too large.

Here’s a refactored version:

```javascript
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import './Calculator.css';
import calculate from '../logic/calculate';

const Button = ({ value, className, onClick }) => (
  <button type="button" className={className} onClick={onClick}>
    {value}
  </button>
);

Button.propTypes = {
  value: PropTypes.string.isRequired,
  className: PropTypes.string,
  onClick: PropTypes.func,
};

Button.defaultProps = {
  className: '',
  onClick: () => {},
};

const buttonConfig = [
  { value: 'AC', className: 'operator' },
  { value: '+/-', className: 'operator' },
  { value: '%', className: 'operator' },
  { value: '÷', className: 'operator' },
  { value: '7' },
  { value: '8' },
  { value: '9' },
  { value: 'x', className: 'operator' },
  { value: '4' },
  { value: '5' },
  { value: '6' },
  { value: '-', className: 'operator' },
  { value: '1' },
  { value: '2' },
  { value: '3' },
  { value: '+', className: 'operator' },
  { value: '0', className: 'zero' },
  { value: '.' },
  { value: '=', className: 'operator' },
];

const Calculator = () => {
  const [calculatorState, setCalculatorState] = useState({
    total: null,
    next: null,
    operation: null,
  });

  const handleClick = (buttonName) => {
    const newState = calculate(calculatorState, buttonName);
    setCalculatorState(newState);
  };

  return (
    <div className="calculator">
      <div className="display">
        {calculatorState.next || calculatorState.total || '0'}
      </div>
      <div className="button-grid">
        {buttonConfig.map(({ value, className = '' }) => (
          <Button
            key={value}
            value={value}
            className={className}
            onClick={() => handleClick(value)}
          />
        ))}
      </div>
    </div>
  );
};

Calculator.propTypes = {
  calculatorState: PropTypes.shape({
    total: PropTypes.string,
    next: PropTypes.string,
    operation: PropTypes.string,
  }),
};

export default Calculator;
```

### To wrap up the key Improvements:
1. **Dynamic Button Generation**: The `buttonConfig` array allows easy modification and expansion of buttons by simply altering the array, reducing repetitive code.
2. **Component Structure**: This structure is cleaner and more modular, making it easier to maintain and scale.
3. **Prop Types Validation**: By using `PropTypes.shape`, you have clearer validation of the `calculatorState` object.
4. **CSS Handling**: While not directly shown, this setup makes it easier to integrate CSS Modules or `styled-components` if needed.
